### ISSUE TITLE
need to find undefined tossi

### ISSUE THREAD

**Issue by Hyeonji-Ryu** [tossicat/tossicat-core#1]
need to find undefined tossi in this grogram.

**Comment by Hyeonji-Ryu** [comment]
already included: ["은", "는", "이", "가", "이다", "다", "으로", "로", "의", "도", "께", "에", "만", "뿐", "보다",
    "같이", "밖에", "부터", "까지", "마냥", "처럼", "마저", "조차", "마냥", "커녕", "을", "를",
    "(으)로", "은(는)", "(는)은", "(이)다", "(을)를", "(를)을", "(이)가", "(가)이"]

**Comment by dialektike** [comment]
@Hyeonji-Ryu There is a problem with the list that does not need to be converted. I subtracted the list to convert from the entire list. It is as follows:

```python
>>> TOSSI_LIST = [
... "은", "는", "이", "가", "이다", "다", "으로", "로", "의", "도", "께", "에", "만", "뿐", "보다",
... "같이", "밖에", "부터", "까지", "마냥", "처럼", "마저", "조차", "마냥", "커녕", "을", "를",
... "(으)로", "은(는)", "(는)은", "(이)다", "(을)를", "(를)을", "(이)가", "(가)이",
... ]
>>> len(TOSSI_LIST)
35
>>> EUL = ("(을)를", "를", "을")
>>> KA = ("(이)가", "가", "이")
>>> IDA = ("(이)다", "다", "이다")
>>> NEUN = ("(은)는", "는", "은")
>>> RO = ("(으)로", "로", "으로")
>>> 
>>> set(TOSSI_LIST) - set(EUL) - set(KA) - set(IDA) - set(NEUN) - set(RO)
{'뿐', '(는)은', '도', '께', '부터', '조차', '의', '마저', '같이', '(가)이', '에', '(를)을', '까지', '은(는)', '마냥', '커녕', '밖에', '처럼', '보다', '만'}
```

Looking at the rest of the list, there seems to be a problem. It seems to contain things that need to be removed.

**Comment by dialektike** [comment]
@Hyeonji-Ryu Please refer to the link below.

https://github.com/tossicat/tossicat-core/commit/97207653c93a1f561bb23afc6b19b4bb10c51f81

**Comment by Hyeonji-Ryu** [comment]
i'm struggling to see the point of this. Could I get more info about the bug you are talking about?
Thank you!

**Comment by dialektike** [comment]
https://github.com/tossicat/tossicat-core/commit/697afd52395a50c99550bd5b12599e592128b4a8
