### ISSUE TITLE
Error 유형 통합을 하면 어떨까요?

### ISSUE THREAD

**Issue by dialektike** [tossicat/tossicat-core#11]
현재 Error 유형이 2개로 분리되어 있습니다. 다음 링크 참고

https://github.com/tossicat/tossicat-core/blob/main/src/error.rs

이걸 하나로 합치면 코드도 줄고 관리도 편할 것 같습니다.
그리고 추가적으로 이 프로젝트는 라이브러리로 이용해 보니 에러 처리하려고 보니 메세지로 주니, 너무 복잡한 것 같습니다.
에러 내용을 직접 내는 것 보다 에러 코드와 같은 것을 반환하면 어떨까요?

**Comment by Hyeonji-Ryu** [comment]
에러 모듈의 경우 에러 코드를 반환하는 형태로 구현이 변경되었습니다. 라이브러리로 바인딩 시 https://github.com/tossicat/tossicat-core/blob/main/docs/errors.md 를 참고 부탁드립니다.
