### ISSUE TITLE
Err 출력에 대한 개선점 논의

### ISSUE THREAD

**Issue by dialektike** [tossicat/tossicat-core#12]
`main.rs`에 들어 있는 것을 실행하면 다음과 같습니다.

```
테스트 문장: "{철수, 은} {영희,   과} {밥,  를} {나물, 코코} 먹습니다."
결과 문장: Err(ParseError { error: InvalidValue(InvalidTossi), description: "201(101)." })
```

1. 이때 `description`이라는 단어가 적절하지 않은 것 같습니다. `code' 정도로 바꾸면 어떨까요? 
2. `201(101).`에서 `.`를 빼면 좋을 것 같습니다.
3. `201(101).`에서 괄호를 다른 것으로 바꾸는 것이 이 라이브러리를 사용하는 사람이 더 편하게 에러 코드를 파싱할 수 있을 것 같습니다. 저는 `201<101` 또는 `201>101`과 같이 하면 좋을 것 같습니다. 현재 숫자로 그 의미를 파악할 수 있기 때문에 `201:101`도 나쁘지 않을 것 같습니다.

**Comment by Hyeonji-Ryu** [comment]
네. 해당 이슈 확인해보겠습니다.
