### ISSUE TITLE
`available_tossi_list.md` 파일 내용 검토해주세요.

### ISSUE THREAD

**Issue by dialektike** [tossicat/tossicat-core#13]
현재 프로젝트가 다룰 수 있는 토시에 관련된 내용을 작성했습니다. 다음 링크입니다.

https://github.com/tossicat/tossicat-core/blob/main/docs/available_tossi_list.md

윗 파일을 직접 수정하지 마시고 문제가 있는 문장을 여기에 답글을 달라 주세요.

아니면 윗 파일을 간접적으로 생성하는 아래 스크립트를 수정해주세요.

https://github.com/tossicat/tossicat-core/blob/docs/python_scripts/automatic_list_creation.py

**Comment by Hyeonji-Ryu** [comment]
검토 완료하였습니다.
