### ISSUE TITLE
토씨 선택 기능 추가

### ISSUE THREAD

**Issue by item4** [tossicat/tossicat-core#16]
안녕하세요. Python tossi의 대체품을 찾다가 본 프로젝트를 알게되었습니다.

다름이 아니라 tossicat-core와 tossicat-python에 다음 기능을 할 수 있는 함수가 없다는걸 알게 되어 도움을 구하고자 합니다.

Example
======

```py
name = "철수"
postfix = tossi.pick(name, "은는")
print(f"저기 있는 <strong>{name}</strong>{postfix} 답을 알고 있단다.")  # 저기 있는 <strong>철수</strong>는 답을 알고 있단다
```

다음과 같이 단어에 HTML이나 Markdown 같은 서식을 곁들이고 싶은 경우의 처리방법이 필요합니다.

**Comment by dev-bearabbit** [comment]
안녕하세요,
메일을 늦게 확인해서 이제서야 답변 보내드립니다..!

가능하다면 다음주 중에 요청주신 함수도 추가 개발해보겠습니다.
감사합니다 :)

-----Original Message-----
From: "item4(Kim ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-10-29 (화) 11:36:10 (GMT+09:00)
Subject: [tossicat/tossicat-core] 토씨 선택 기능 추가 (Issue #16)

안녕하세요. Python tossi의 대체품을 찾다가 본 프로젝트를 알게되었습니다.
다름이 아니라 tossicat-core와 tossicat-python에 다음 기능을 할 수 있는 함수가 없다는걸 알게 되어 도움을 구하고자 합니다.
Example
name = "철수" postfix = tossi.pick(name, "은는") print(f"저기 있는 <strong>{name}</strong>{postfix} 답을 알고 있단다.") # 저기 있는 <strong>철수</strong>는 답을 알고 있단다
다음과 같이 단어에 HTML이나 Markdown 같은 서식을 곁들이고 싶은 경우의 처리방법이 필요합니다.

**Comment by dev-bearabbit** [comment]
안녕하세요!

요청주신 기능 개발이 완료되어 공유드립니다 :)
transform라는 함수가 추가되었으며, 사용법은 아래 문서 참고 부탁드립니다.

https://github.com/tossicat/tossicat-python

사용하시다가 이슈 생기면 편하게 연락주세요!
감사합니다 :)

-----Original Message-----
From: "item4(Kim ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-10-29 (화) 11:36:10 (GMT+09:00)
Subject: [tossicat/tossicat-core] 토씨 선택 기능 추가 (Issue #16)

안녕하세요. Python tossi의 대체품을 찾다가 본 프로젝트를 알게되었습니다.
다름이 아니라 tossicat-core와 tossicat-python에 다음 기능을 할 수 있는 함수가 없다는걸 알게 되어 도움을 구하고자 합니다.
Example
name = "철수" postfix = tossi.pick(name, "은는") print(f"저기 있는 <strong>{name}</strong>{postfix} 답을 알고 있단다.") # 저기 있는 <strong>철수</strong>는 답을 알고 있단다
다음과 같이 단어에 HTML이나 Markdown 같은 서식을 곁들이고 싶은 경우의 처리방법이 필요합니다.
