### ISSUE TITLE
"누구"에 "~가"를 붙일 경우, "누구가"가 됩니다. 그러나 "누가"와 같이 변해야 합니다. 

### ISSUE THREAD

**Issue by dialektike** [tossicat/tossicat-core#3]
제목에서 설명한 것도 있지만, 아래와 같이 3개가 더 있습니다.

> ‘가’가 붙을 때 형태가 변하는 예가 있다. ‘누구’와 ‘가’가 함께 쓰이면 ‘누가’로 쓰며, ‘너, 나, 저’와 같이 쓸 때는 ‘네가, 내가, 제가’로 쓴다.

처리하기는 쉽지 않지만, 어떻게 어디서 처리할지 결정해야 합니다. 예를 들어 들어온 단어를 바꿔서 리턴해야 하는지 결정해야 합니다.

**Comment by dialektike** [comment]
아래 같은 조사는 위와 같이 변하지 않습니다.

`~ 와`: 조사모음으로 끝나는 체언에 붙어, ① 다른 말과 비교함을 나타내는 부사격 조사. ‘와’ 성분이 반드시 주어 또는 목적어 뒤에 나타남. 너는 키가 나∼ 같다 | 나는 너∼ 성격이 다르다.

**Comment by Hyeonji-Ryu** [comment]
해당 이슈의 경우 pick() 함수에서는 적용될 수 없습니다.
이에 Pick()이라는 함수를 제외하고 대명사를 처리하는 로직 추가개발이 진행될 예정입니다.
감사합니다 :)

**Comment by dialektike** [comment]
@Hyeonji-Ryu 저번에 논의한 것처럼 `pick()`제거 했습니다.

https://github.com/tossicat/tossicat-core/commit/4910f8334151f0445c20f61263b2e431128a1f32

**Comment by dialektike** [comment]
이 이슈 해결하기 위한 작업 시작

https://github.com/tossicat/tossicat-core/commit/256c8d5c2f7670eae03a95b5664a04b647ad1e27

현재 테스트는 다 통과했습니다. 테스트 코드 보완하고 설명을 보완하면 이 이슈 제거하겠습니다.

**Comment by dialektike** [comment]
완료

https://github.com/tossicat/tossicat-core/commit/d17ed7e330773d0f286c53fb3c0448c61db7fec4
