### ISSUE TITLE
에러 반환 컨벤션을 맞춰야 합니다.

### ISSUE THREAD

**Issue by Hyeonji-Ryu** [tossicat/tossicat-core#7]
현재 pick(), postfix()의 경우 에러를 반환하지 않으며, value_verifier()를 선행해야 에러를 잡을 수 있도록 구성했습니다. 
또한 에러 반환도 String으로 반환하도록 설정했습니다. 
하지만 modify_sentence()는 로직 자체에 에러 반환이 있어 컨벤션이 맞지 않습니다.

**Comment by dialektike** [comment]
이번에 `modify_sentence()`에 작성하다 보니,

> 현재 pick(), postfix()의 경우 에러를 반환하지 않으며, value_verifier()를 선행해야 에러를 잡을 수 있도록 구성했습니다.

이 구성이 한 가지 일을 하는데 결국 거의 같은 루틴을 두 번 돌리게 되는 것을 알게 되었습니다. 예를 들어 `pick()` 함수를 사용하기 위해서 미리 `value_verifier()` 함수이 작동한 결과를 보고 판단해야 해야 하는 것이죠. 문제가 있으면 좋지만, 문제가 없어 `pick()` 함수를 돌리기로 결정했다면 결국 거의 같은 루틴이 두 번 들어가게 되는 것입니다.

이게  `modify_sentence()`을 수행하다 보면 더 문제가 심각해 집니다. 문장 안에 변환해야 할 것이 3개 이상 있다면, 총 6번을 돌아야 한다는 결론에 이릅니다. 3번만 돌리면 되는데 말이죠.

제 생각으로는 `pick()`, `postfix()` 함수을 변경하는 편이 더 좋을 것 같습니다.

**Comment by dialektike** [comment]
> 현재 pick(), postfix()의 경우 에러를 반환하지 않으며, value_verifier()를 선행해야 에러를 잡을 수 있도록 구성했습니다.
> 또한 에러 반환도 String으로 반환하도록 설정했습니다.

이 문제는 그리 어렵지 않습니다. `modify_sentence()`에서 에러 반환을 하도록 `String` 형식으로 반환하게 하면 됩니다.

**Comment by dialektike** [comment]
그리고 `value_verifier()`을 `String` 형식으로 반환하게 되면서 이 라이브러리를 기반으로 만들고 있는 [tossicat-cmd](https://github.com/tossicat/tossicat-cmd)에서 다음과 같은 문제점이 발생하고 있습니다.

```rust
fn main() {
    let args = Args::parse();
    // 아래 값을 `Some(true)`으로 설정해야 이 `only_tossi`을 넣지 않더라고
    // `false`라고 인식하여 단어와 프로그램이 찾는 적절한 토시를 합쳐서 출력하게 된다.
    // if args.only_tossi == Some(true) {
    //     println!("{}", pick(&args.word, &args.tossi));
    // } else {
    //     println!("{}", postfix(&args.word, &args.tossi));
    // }
    let temp_verifier = value_verifier(&args.word, &args.tossi);
    if args.only_tossi == Some(true) {
        if temp_verifier == Ok(()) {
            println!("{}", pick(&args.word, &args.tossi));
        } else {
            println!("{:?}", temp_verifier);
        }
    } else {
        if temp_verifier == Ok(()) {
            println!("{}", postfix(&args.word, &args.tossi));
        } else {
            println!("{:?}", temp_verifier);
        }
    }
}
```

원 코드 링크 참고

https://github.com/tossicat/tossicat-cmd/blob/9e4005577c686e8d0224290feffe94ceec0c2e5d/src/main.rs#L34

**Comment by dialektike** [comment]
@Hyeonji-Ryu 님의 아래 Commit 으로 pick(), postfix()의 에러 반환 컨벤션을 맞췄습니다.

https://github.com/tossicat/tossicat-core/commit/57c9c23401e32ee293d7fdb3c88b97fe90d418f3
