### ISSUE TITLE
`verify_value()`에서 word에 한글 아닌 것이 들어 왔을 때 처리 문제

### ISSUE THREAD

**Issue by dialektike** [tossicat/tossicat-core#9]
원래 아래 테스트가 있었던 같습니다.
이게 한글이 안 들어오면 에러가 나는지 확인하는 코드 였던 것 같네요.

```rust
println!("결과: {:?}", value_verifier("apple", "은"));
println!("결과: {:?}", value_verifier("apple", "는"));
println!("결과: {:?}", value_verifier("apple", "is")); 
```

위 함수가 `verify_value()`로 변하면서 위 테스트가 사라졌더군요. 그런데 문제는 이 함수가 영어를 걸러내지 못하는 것 같습니다.

```rust
let word = "Cocoa";
let tossi = "까지";
assert_eq!(Ok(()), verify_value(word, tossi));
```

원래 가능하지 않았나요? 이 쪽 부분이 너무 많이 바뀌고, 이 함수의 문서는 예전 것이 그대로 있어서 어떻게 변한 것인지 정확하게 모르겠습니다.

```rust
/// 변환하기 전에 입력된 것들이 변환가능한 것인지 검사하는 함수
/// 위에서부터 아래 조건 문을 순서대로 살펴 보겠다.
///
/// 1. 단어는 마지막 글자가 한글이나 숫자이면 된다.
/// 2. 토시는 한글이면 된다.
/// 3. 변환할 수 있는 토시인지 아닌지 파악한다.
/// 4. 단어의 길이가 50자를 넘으면 처리하지 않도록 처리한다.
///
/// 이 4가지를 만족하면 본 작업인 글자에 맞게 토시를 변환하게 된다.
/// 이 함수의 사용법은 `tests/lib.rs`에서 `verifiers()`를 테스트 하는
/// `_verifiers()` 부분을 살펴보시면 됩니다.
///
///
pub fn verify_value<'a>(word: &'a str, tossi: &'a str) -> Result<(), ValueErrorType> {
    if !is_verifier_tossi(tossi) {
        Err(ValueErrorType::InvalidTossi)
    } else if over_limit_word_len(word) {
        Err(ValueErrorType::LimitLength)
    } else {
        Ok(())
    }
}
```

윗 코드 원본 링크

https://github.com/tossicat/tossicat-core/blob/e76726010d4db7605591a8ef4ef5b8c7a1262f07/src/verifier.rs#L124

**Comment by Hyeonji-Ryu** [comment]
영어 테스트 결과 제대로 에러를 반환하는 것으로 확인됩니다.
<img width="691" alt="스크린샷 2023-01-15 오후 7 41 51" src="https://user-images.githubusercontent.com/42489770/212536122-c9d5198b-847d-4a52-bf2e-46ecfa2f3e37.png">
varifiers는 모두 pick, postfix에 포함되어 있습니다.
<img width="691" alt="스크린샷 2023-01-15 오후 7 41 57" src="https://user-images.githubusercontent.com/42489770/212536130-15d844a3-42af-48d4-a06f-3e1565b016f8.png">
